/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as LearnCategoryPostRouteImport } from './routes/learn.$category.$post'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as ApiPublicHooksAppointmentRemindersRouteImport } from './routes/api/public/hooks/appointment-reminders'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LearnCategoryPostRoute = LearnCategoryPostRouteImport.update({
  id: '/learn/$category/$post',
  path: '/learn/$category/$post',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/admin/providers',
    path: '/admin/providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksAppointmentRemindersRoute =
  ApiPublicHooksAppointmentRemindersRouteImport.update({
    id: '/api/public/hooks/appointment-reminders',
    path: '/api/public/hooks/appointment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/learn/$category/$post': typeof LearnCategoryPostRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/learn': typeof LearnIndexRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/learn/$category/$post': typeof LearnCategoryPostRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/learn/': typeof LearnIndexRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/learn/$category/$post': typeof LearnCategoryPostRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/map'
    | '/reset-password'
    | '/services'
    | '/profile'
    | '/provider'
    | '/learn/'
    | '/admin/providers'
    | '/learn/$category/$post'
    | '/api/public/hooks/appointment-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/map'
    | '/reset-password'
    | '/services'
    | '/profile'
    | '/provider'
    | '/learn'
    | '/admin/providers'
    | '/learn/$category/$post'
    | '/api/public/hooks/appointment-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/map'
    | '/reset-password'
    | '/services'
    | '/_authenticated/profile'
    | '/_authenticated/provider'
    | '/learn/'
    | '/_authenticated/admin/providers'
    | '/learn/$category/$post'
    | '/api/public/hooks/appointment-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnCategoryPostRoute: typeof LearnCategoryPostRoute
  ApiPublicHooksAppointmentRemindersRoute: typeof ApiPublicHooksAppointmentRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/learn/$category/$post': {
      id: '/learn/$category/$post'
      path: '/learn/$category/$post'
      fullPath: '/learn/$category/$post'
      preLoaderRoute: typeof LearnCategoryPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/appointment-reminders': {
      id: '/api/public/hooks/appointment-reminders'
      path: '/api/public/hooks/appointment-reminders'
      fullPath: '/api/public/hooks/appointment-reminders'
      preLoaderRoute: typeof ApiPublicHooksAppointmentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnCategoryPostRoute: LearnCategoryPostRoute,
  ApiPublicHooksAppointmentRemindersRoute:
    ApiPublicHooksAppointmentRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
